
/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2021-01-29 09:41:02
*/
`include "/home/ma/ef/openlane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/verilog/primitives.v"
`include "/home/ma/ef/openlane/pdks/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"
`include "/home/ma/ef/Fault-SPM/openlane/spm_top/runs/spm_top/results/dft/spm_top.tap.v"

module testbench;
    wire[0:0] \tdo ;
    reg[31:0] \mp ;
    wire[0:0] \done ;
    reg[0:0] \start ;
    wire[63:0] \prod ;
    reg[0:0] \rst ;
    reg[31:0] \mc ;
    wire[0:0] \tdo_paden_o ;
    reg[0:0] \tms ;
    reg[0:0] \tck ;
    reg[0:0] \tdi ;
    reg[0:0] \trst ;
    reg[0:0] \clk ;

    
    always #1 clk = ~clk;
    always #1 tck = ~tck;

    spm_top uut(
        .\tdo ( \tdo ) , .\mp ( \mp ) , .\done ( \done ) , .\start ( \start ) , .\prod ( \prod ) , .\rst ( \rst ) , .\mc ( \mc ) , .\tdo_paden_o ( \tdo_paden_o ) , .\tms ( \tms ) , .\tck ( \tck ) , .\tdi ( \tdi ) , .\trst ( \trst ) , .\clk ( \clk ) 
    );

    integer i, error;

    reg [266:0] scanInSerial;
    reg [266:0] vectors [0:19];
    reg [266:0] gmOutput[0:19];

    wire[7:0] tmsPattern = 8'b 01100110;
    wire[3:0] preloadChain = 4'b 0011;

    initial begin
        // $dumpfile("dut.vcd"); // DEBUG
        // $dumpvars(0, testbench);
        \clk = 1 ;
        \rst = 1 ;
        \mc = 0 ;
        \mp = 0 ;
        \clk = 0 ;
        \rst = 1 ;
        \start = 0 ;
        \tms = 1 ;
        \tck = 0 ;
        \tdi = 0 ;
        \trst = 0 ;

        $readmemb("spm_top.bin.vec.bin", vectors);
        $readmemb("spm_top.bin.out.bin", gmOutput);
        #50;
        rst = ~rst;
        trst = 1;        
        #50;
        test(vectors[0], gmOutput[0]) ;
        #1 ; 
        test(vectors[1], gmOutput[1]) ;
        #1 ; 
        test(vectors[2], gmOutput[2]) ;
        #1 ; 
        test(vectors[3], gmOutput[3]) ;
        #1 ; 
        test(vectors[4], gmOutput[4]) ;
        #1 ; 
        test(vectors[5], gmOutput[5]) ;
        #1 ; 
        test(vectors[6], gmOutput[6]) ;
        #1 ; 
        test(vectors[7], gmOutput[7]) ;
        #1 ; 
        test(vectors[8], gmOutput[8]) ;
        #1 ; 
        test(vectors[9], gmOutput[9]) ;
        #1 ; 
        test(vectors[10], gmOutput[10]) ;
        #1 ; 
        test(vectors[11], gmOutput[11]) ;
        #1 ; 
        test(vectors[12], gmOutput[12]) ;
        #1 ; 
        test(vectors[13], gmOutput[13]) ;
        #1 ; 
        test(vectors[14], gmOutput[14]) ;
        #1 ; 
        test(vectors[15], gmOutput[15]) ;
        #1 ; 
        test(vectors[16], gmOutput[16]) ;
        #1 ; 
        test(vectors[17], gmOutput[17]) ;
        #1 ; 
        test(vectors[18], gmOutput[18]) ;
        #1 ; 
        test(vectors[19], gmOutput[19]) ;
        #1 ; 

        $display("SUCCESS_STRING");
        $finish;
    end

    task test;
        input [266:0] vector;
        input [266:0] goldenOutput;
        begin
           
            // Preload Scan-Chain with TV

            shiftIR(preloadChain);
            enterShiftDR();

            for (i = 0; i < 267; i = i + 1) begin
                tdi = vector[i];
                if (i == 264) begin
                    tms = 1; // Exit-DR
                end
                if (i == 265) begin
                    tms = 0; // Pause-DR
                end
                if (i == 266) begin
                    tms = 1; // Exit2-DR
                end
                #2;
            end

            tms = 0; // Shift-DR
            #2;
            // Shift-out response
            error = 0;
            #3;
            for (i = 0; i< 267;i = i + 1) begin
                tdi = 0;
                scanInSerial[i] = tdo;
                if (scanInSerial[i] != goldenOutput[i]) begin
                    $display("Error simulating output response at bit number %0d                        Expected %0b, Got %0b", i, goldenOutput[i], scanInSerial[i]);
                    error = error + 1;
                end
                if(i == 266) begin
                    tms = 1; // Exit-DR
                end
                #2;
            end
            tms = 1; // update-DR
            #2;
            tms = 0; // run-test-idle
            #2;

            if(scanInSerial != goldenOutput) begin
                $display("Simulating TV failed, number fo errors %0d : ", error);
                $error("SIMULATING_TV_FAILED");
                $finish;
            end
        end
    endtask

       task shiftIR;
        input[3:0] instruction;
        integer i;
        begin
            for (i = 0; i< 5; i = i + 1) begin
                tms = tmsPattern[i];
                #2;
            end

            // At shift-IR: shift new instruction on tdi line
            for (i = 0; i < 4; i = i + 1) begin
                tdi = instruction[i];
                if(i == 3) begin
                    tms = tmsPattern[5];     // exit-ir
                end
                #2;
            end

            tms = tmsPattern[6];     // update-ir 
            #2;
            tms = tmsPattern[7];     // run test-idle
            #6;
        end
    endtask

    task enterShiftDR;
        begin
            tms = 1;     // select DR
            #2;
            tms = 0;     // capture DR -- shift DR
            #4;
        end
    endtask

    task exitDR;
        begin
            tms = 1;     // Exit DR -- update DR
            #4;
            tms = 0;     // Run test-idle
            #2;
        end
    endtask
endmodule
