/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2021-01-29 09:41:01
*/

/* Need to export PDK_ROOT */
`include "libs.ref/sky130_fd_sc_hd/verilog/primitives.v"
`include "libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"

`ifdef GL
    `include "gl/user_proj_top.v"
`else
    `include "dft/2-user_proj_top.tap.v"
`endif

module testbench;
    wire[169:0] \tie ;
    reg[0:0] \clk ;
    reg[0:0] \tdi ;
    wire[0:0] \done ;
    reg[0:0] \trst ;
    reg[31:0] \mc ;
    reg[0:0] \start ;
    wire[0:0] \tdo ;
    reg[0:0] \rst ;
    reg[0:0] \tck ;
    wire[0:0] \tdo_paden_o ;
    reg[31:0] \mp ;
    wire[63:0] \prod ;
    reg[0:0] \tms ;


    always #1 clk = ~clk;
    always #1 tck = ~tck;

    user_proj_top uut(
    `ifdef USE_POWER_PINS
        .VPWR(1'b1),
        .VGND(1'b0),
    `endif
        .\tie ( \tie ) , .\clk ( \clk ) , .\tdi ( \tdi ) , .\done ( \done ) , .\trst ( \trst ) , .\mc ( \mc ) , .\start ( \start ) , .\tdo ( \tdo ) , .\rst ( \rst ) , .\tck ( \tck ) , .\tdo_paden_o ( \tdo_paden_o ) , .\mp ( \mp ) , .\prod ( \prod ) , .\tms ( \tms ) 
    );    

    integer i;

    wire[501:0] serializable =
        502'b1010110101101111001111101100111011011111011100101101011100110101011001001100110001000000000100001010010001001011001011101111110001101111111001101011111000101001111011001001110001100011001011101010010100100010110111101101011001111100010000110110101110100010110110101010011110110011100100011111001110111101110101111010110000010001000111010010001111111000110101011101110000011000001110010111101110000111111010010111001010011110100010011011001100100101100000011011001000110011010110111111100101011101101100;
    reg[501:0] serial;

    wire[7:0] tmsPattern = 8'b 01100110;
    wire[3:0] preload_chain = 4'b0011;

    initial begin
        // $dumpfile("dut.vcd");
        // $dumpvars(0, testbench);
        \mc = 0 ;
        \mp = 0 ;
        \clk = 0 ;
        \rst = 1 ;
        \start = 0 ;
        \tms = 0 ;
        \tck = 0 ;
        \tdi = 0 ;
        \trst = 0 ;

        tms = 1;
        #2;
        rst = ~rst;
        trst = 1;        
        #2;

        /*
            Test PreloadChain Instruction
        */
        shiftIR(preload_chain);
        enterShiftDR();

        for (i = 0; i < 502; i = i + 1) begin
            tdi = serializable[i];
            #2;
        end
        for(i = 0; i< 502; i = i + 1) begin
            serial[i] = tdo;
            #2;
        end 

        if(serial !== serializable) begin
            $error("EXECUTING_PRELOAD_CHAIN_INST_FAILED");
            $finish;
        end
        exitDR();

        $display("SUCCESS_STRING");
        $finish;
    end

    task shiftIR;
        input[3:0] instruction;
        integer i;
        begin
            for (i = 0; i< 5; i = i + 1) begin
                tms = tmsPattern[i];
                #2;
            end

            // At shift-IR: shift new instruction on tdi line
            for (i = 0; i < 4; i = i + 1) begin
                tdi = instruction[i];
                if(i == 3) begin
                    tms = tmsPattern[5];     // exit-ir
                end
                #2;
            end

            tms = tmsPattern[6];     // update-ir 
            #2;
            tms = tmsPattern[7];     // run test-idle
            #6;
        end
    endtask

    task enterShiftDR;
        begin
            tms = 1;     // select DR
            #2;
            tms = 0;     // capture DR -- shift DR
            #4;
        end
    endtask

    task exitDR;
        begin
            tms = 1;     // Exit DR -- update DR
            #4;
            tms = 0;     // Run test-idle
            #2;
        end
    endtask
endmodule
