/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2021-01-29 09:40:43
*/

/* Need to export PDK_ROOT */
`include "libs.ref/sky130_fd_sc_hd/verilog/primitives.v"
`include "libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"

`include "dft/1-user_proj_top.chained.v"

module testbench;
    reg[31:0] \mp ;
    reg[0:0] \test ;
    reg[0:0] \start ;
    wire[169:0] \tie ;
    reg[0:0] \sin ;
    wire[0:0] \done ;
    reg[0:0] \tck ;
    reg[0:0] \shift ;
    reg[31:0] \mc ;
    reg[0:0] \rst ;
    wire[0:0] \sout ;
    reg[0:0] \clk ;
    wire[63:0] \prod ;

        always #1 clk = ~clk; 
        always #1 tck = ~tck; 

    user_proj_top uut(
        .\mp ( \mp ) , .\test ( \test ) , .\start ( \start ) , .\tie ( \tie ) , .\sin ( \sin ) , .\done ( \done ) , .\tck ( \tck ) , .\shift ( \shift ) , .\mc ( \mc ) , .\rst ( \rst ) , .\sout ( \sout ) , .\clk ( \clk ) , .\prod ( \prod ) 
    ); 

    wire[501:0] serializable =
        502'b0100110100001101000011010011110001010111111101010011111001001010000011011110101011000000001100011111100100000000000001101000000010101111111001010010101110100001010111010011000100111101011001101101110110101011111011001101001010101000000011000010001100100111100101111100010111110111111100011001110111111111110001001001111011111000001101011011000001111000000100110101000011101100010000100010100110001100100000101110110001000010000111100000110110001101101001010001000000001000111100011100000001000000100111;
    reg[501:0] serial;
    integer i;
    initial begin
        // $dumpfile("chain.vcd");
        // $dumpvars(0, testbench);
        \mc = 0 ;
        \mp = 0 ;
        \clk = 0 ;
        \rst = 1 ;
        \start = 0 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #10;
        rst = ~rst;
        shift = 1;
        test = 1;
        for (i = 0; i < 502; i = i + 1) begin
            sin = serializable[i];
            #2;
        end
        for (i = 0; i < 502; i = i + 1) begin
            serial[i] = sout;
            #2;
        end
        if (serial === serializable) begin
            $display("SUCCESS_STRING");
        end
        $finish;
    end
endmodule
